flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- GLFW-b-1.4.8.1
- bindings-GLFW-3.1.2.3
resolver: lts-9.12

nix:
  enable: true
  pure: true
# mesa_glu

# glut
# glide?
# glm?
# lablgl?
# libglade?
# libglademm
# python3.6-pyopengl
# xf86-video-glint

  packages: [glew, mesa, freeglut]
